networks:
  rip-in-c-ax-net:
    ipam:
      config:
        - subnet: 10.12.10.0/24
  rip-in-c-ab-net:
    ipam:
      config:
        - subnet: 10.12.1.0/24
  rip-in-c-bc-net:
    ipam:
      config:
        - subnet: 10.12.2.0/24
  rip-in-c-ac-net:
    ipam:
      config:
        - subnet: 10.12.4.0/24
  rip-in-c-ac2-net:
    ipam:
      config:
        - subnet: 10.12.5.0/24
  rip-in-c-cy-net:
    ipam:
      config:
        - subnet: 10.12.20.0/24

services:
  # --- CLIENT rete AX ---
  client_ax:    
    image: ubuntu:22.04
    container_name: client-AX
    networks:
      rip-in-c-ax-net:
        ipv4_address: 10.12.10.99
    command: >
      bash -c "apt-get update && apt-get install -y traceroute iputils-ping iproute2 &&
      ip route del default &&
      ip route add default via 10.12.10.254 &&
      tail -f /dev/null"
    cap_add:
      - NET_ADMIN # Necessario per modificare la tabella di routing del container

  # --- ROUTER A ---
  router_a:    
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: router-A
    networks:
      rip-in-c-ax-net:
        ipv4_address: 10.12.10.254
    #  rip-in-c-ab-net:
    #    ipv4_address: 10.12.1.3
    #  rip-in-c-ac-net:
    #    ipv4_address: 10.12.4.2
    volumes:
      - ../configs/router-A.conf:/app/router.conf
    sysctls:
      - net.ipv4.ip_forward=1 # ABILITA IL ROUTING DI LINUX
    cap_add:
      - NET_ADMIN
    command: tail -f /dev/null

  # --- ROUTER B ---
  router_b:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: router-B
    networks:
    #  rip-in-c-ab-net:
    #    ipv4_address: 10.12.1.2
      rip-in-c-bc-net:
        ipv4_address: 10.12.2.2
    volumes:
      - ../configs/router-B.conf:/app/router.conf
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    command: tail -f /dev/null

  # --- ROUTER C ---
  router_c:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: router-C
    networks:
      rip-in-c-bc-net:
        ipv4_address: 10.12.2.3
      rip-in-c-cy-net:
        ipv4_address: 10.12.20.254
      #rip-in-c-ac-net:
        #ipv4_address: 10.12.4.3      
    volumes:
      - ../configs/router-C.conf:/app/router.conf
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    command: tail -f /dev/null

  # --- CLIENT rete CY ---
  client_cy:
    image: ubuntu:22.04
    container_name: client-CY
    networks:
      rip-in-c-cy-net:
        ipv4_address: 10.12.20.99
    command: >
      bash -c "apt-get update && apt-get install -y iputils-ping traceroute iproute2 &&
      ip route del default &&
      ip route add default via 10.12.20.254 &&
      tail -f /dev/null"
    cap_add:
      - NET_ADMIN